server:
  port: 8888

spring:
  application:
    name: carlosliu_blog
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/carlosliu_blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
      username: root
      password: s300056.

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: